AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'vendor/**/*'
    - 'db/**/*'
    - 'script/**/*'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
    - 'config/puma.rb'
    - 'config/spring.rb'
    - 'config/environments/*'
    - 'config/initializers/simple_form_bootstrap.rb'
    - 'config/initializers/simple_form.rb'
    - 'config/initializers/devise.rb'
    - 'Gemfile'
    - 'bin/**'
    - 'spec/**/*.rb'
  UseCache: false
  TargetRailsVersion: 5.1
Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
Documentation:
  Enabled: false
